---
abstract: 'Perl library with MINIMAL interface to use MailChimp API.'
author:
  - 'Michele Beltrame <mb@blendgroup.it>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'Dist::Zilla version 6.030, CPAN::Meta::Converter version 2.150010'
license: artistic_2
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Net-MailChimp
requires:
  Mojolicious: '9.28'
  Moo: '2'
  Test::Exception: '0'
  namespace::clean: '0.27'
  perl: v5.36.0
  version: '0'
version: 0.1.0
x_generated_by_perl: v5.38.0
x_serialization_backend: 'YAML::Tiny version 1.74'
x_spdx_expression: Artistic-2.0
